name: Achievements
version: '${project.version}'
main: dk.bondegaard.achievements.Main
authors: [ Bondegaard ]
softdepend:
  - Vault
commands:
  aach:
    description: "Admin command for Achievements"
    permission: "achievements.admin"
    usage: "/aach"
    permission-message: "You do not have permission to use this command"
